import { Component } from '@angular/core';
import { Sale } from '../../interfaces/sale';

@Component({
  selector: 'app-ventas',
  templateUrl: './ventas.component.html',
  styleUrl: './ventas.component.css',
})
export class VentasComponent {
  sales: Sale[] = [
    {
      id: 1,
      customer: 'Sergio de Jesus Salazar Cabrera',
      productSold: 'Lampara Moderna',
      dateTime: '19/09/23',
      cost: 599.0,
      email: 'chekho@gmail.com',
      paymentType: 'Tarjeta',
    },
    {
      id: 2,
      customer: 'Jose Angel Ramirez Almeida',
      productSold: 'Lampara de Mesa',
      dateTime: '01/10/24',
      cost: 119.5,
      email: 'angel@gmail.com',
      paymentType: 'Tarjeta',
    },
    {
      id: 3,
      customer: 'Adrian Dario Bravo Luna',
      productSold: 'Lampara de Techo',
      dateTime: '13/12/22',
      cost: 340.5,
      email: 'dario@gmail.com',
      paymentType: 'Paypal',
    },
    {
      id: 4,
      customer: 'Alexa Guerrero Lopez',
      productSold: 'Lamparas Colgantes',
      dateTime: '02/02/24',
      cost: 250.5,
      email: 'alexa@gmail.com',
      paymentType: 'Tarjeta',
    },
    {
      id: 5,
      customer: 'Angel Eduardo Juarez Alvizo',
      productSold: 'Lampara Exteriores',
      dateTime: '18/11/24',
      cost: 399,
      email: 'alvizo@gmail.com',
      paymentType: 'Paypal',
    },
    {
      id: 6,
      customer: 'Sergio de Jesus Salazar Cabrera',
      productSold: 'Lampara Moderna',
      dateTime: '23/03/24',
      cost: 599.0,
      email: 'chekho@gmail.com',
      paymentType: 'Paypal',
    },
    {
      id: 7,
      customer: 'Jose Angel Ramirez Almeida',
      productSold: 'Lampara de Mesa',
      dateTime: '12/10/24',
      cost: 119.5,
      email: 'angel@gmail.com',
      paymentType: 'Tarjeta',
    },
    {
      id: 8,
      customer: 'Adrian Dario Bravo Luna',
      productSold: 'Lampara de Techo',
      dateTime: '23/01/24',
      cost: 340.5,
      email: 'dario@gmail.com',
      paymentType: 'Paypal',
    },
    {
      id: 9,
      customer: 'Alexa Guerrero Lopez',
      productSold: 'Lamparas Colgantes',
      dateTime: '22/11/24',
      cost: 250.5,
      email: 'alexa@gmail.com',
      paymentType: 'Tarjeta',
    },
    {
      id: 10,
      customer: 'Alexa Guerrero Lopez',
      productSold: 'Lamparas Colgantes',
      dateTime: '31/12/24',
      cost: 250.5,
      email: 'alexa@gmail.com',
      paymentType: 'Paypal',
    },
    {
      id: 11,
      customer: 'Angel Eduardo Juarez Alvizo',
      productSold: 'Lampara Exteriores',
      dateTime: '12/10/24',
      cost: 399,
      email: 'alvizo@gmail.com',
      paymentType: 'Tarjeta',
    },
    {
      id: 12,
      customer: 'Angel Eduardo Juarez Alvizo',
      productSold: 'Lampara Exteriores',
      dateTime: '12/10/24',
      cost: 399,
      email: 'alvizo@gmail.com',
      paymentType: 'Paypal',
    },
  ];
}
